# Generated by Django 3.2.18 on 2023-05-23 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230514_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Content must have at least 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, message='Name must have at least 3 characters.'), django.core.validators.MaxLengthValidator(20, message='Name cannot exceed 20 characters.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Subject must have at least 10 characters.'), django.core.validators.MaxLengthValidator(100, message='Subject cannot exceed 100 characters.')]),
        ),
    ]
