# Generated by Django 3.2.18 on 2023-05-07 20:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(help_text='Please provide a descriptive title for your post.', max_length=100, unique=True)),
                ('content', models.TextField(help_text='Please provide your Website Values content on this field.')),
            ],
        ),
    ]
