# Generated by Django 3.2.18 on 2023-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='image_description',
            field=models.CharField(blank=True, help_text='Please provide a description for the image.', max_length=100, null=True),
        ),
    ]
