# Generated by Django 3.2.18 on 2023-04-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_date',
        ),
    ]
