# Generated by Django 3.2.18 on 2023-05-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230506_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='Select a relevant Category that aligns with your story.', on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text="Share your inspiring cancer story with us. Your words can make a difference in someone's life."),
        ),
        migrations.AlterField(
            model_name='post',
            name='describe_image',
            field=models.CharField(default='This is a default image.', help_text='Provide a short image description by removing the default text.', max_length=70),
        ),
    ]
